### ISSUE TITLE
Export is not valid JSON

### ISSUE THREAD

**Issue by lcrocker** [andzdroid/mongo-express#125]
The "Export Collection" button produces a file named "colname.json" containing multiple objects, e.g.:

    {"_id":{ "$oid": "563aaf847454541de84a9e9c" },"number":1}
    {"_id":{ "$oid": "563aaf847454541de84a9e9d" },"number":3}
    {"_id":{ "$oid": "563aaf847454541de84a9e9e" },"number":4}

This is not valid JSON. To correct, add brackets and commas to make the file a list:

    [ {"_id":{ "$oid": "563aaf847454541de84a9e9c" },"number":1} ,
      {"_id":{ "$oid": "563aaf847454541de84a9e9d" },"number":3} ,
      {"_id":{ "$oid": "563aaf847454541de84a9e9e" },"number":4} ]

This should be a pretty trivial change to the exportCollection() function in routes/collection.js. I'd be happy to provide it if it wouldn't interfere with anything I might not know about.

**Comment by wulfsolter** [comment]
Welcome to the wonderful world of JSON ;)

Technically it *is* valid JSON, each new line holds a new object, and this is how mongoexport/mongoimport use it by default. The output should be treated as individual objects separated 
by an EOL character. This makes it easier to have big files that grow such as DB exports and logs without needing another character on the end. In order to have [mongoexport output as array](https://docs.mongodb.org/manual/reference/program/mongoexport/#cmdoption--jsonArray), you would pass the `--jsonArray` flag.

```
mongoexport --db test -c x
connected to: 127.0.0.1
{ "_id" : "54c8f3fb5e24e03c473243c4", "username" : "Aman", "password" : "yesboss" }
{ "_id" : "54c901c1953b434dabadbabf", "username" : "AMAN2" }
exported 2 records

mongoexport --db test -c x --jsonArray
connected to: 127.0.0.1
[{ "_id" : "54c8f3fb5e24e03c473243c4", "username" : "Aman", "password" : "yesboss" },{ "_id" : "54c901c1953b434dabadbabf", "username" : "AMAN2" }]
exported 2 records
```

Since it's a pretty trivial change in code, and I too have wanted this functionality at times, I've added additional button next to "Export" called "[JSON]" that exports as an array. https://github.com/andzdroid/mongo-express/commit/7887028f91b70785a8a9f3406d092d357aa2bf0b

**Comment by lcrocker** [comment]
ECMA-404 is a bit vague on the matter, but RFC 4627 is not: "A JSON text is a serialized object or array." Since Mongo has an option, perhaps this code should have an option, but I think it would be better to just do it the more standard way.

**Comment by wulfsolter** [comment]
Yep. I added the ability to export as both. :) 
<img width="934" alt="screen shot 2015-11-06 at 9 50 44 am" src="https://cloud.githubusercontent.com/assets/1692132/10981311/e797e4d8-846b-11e5-9085-f40379f74667.png">
<img width="897" alt="screen shot 2015-11-06 at 9 50 52 am" src="https://cloud.githubusercontent.com/assets/1692132/10981325/fc1ce9ee-846b-11e5-8de9-ba934ff502de.png">

**Comment by lcrocker** [comment]
Cool. Thanks.

**Comment by wulfsolter** [comment]
It's a pretty common thing I find myself doing - add [ to the start of file, find/replace to search for EOL and add comma, add ] to end of file. Thanks for giving me the push to put it in!
