### ISSUE TITLE
gridFS support

### ISSUE THREAD

**Issue by muxahuk** [andzdroid/mongo-express#156]
Hey, i'v been making gridFS support.
here's whith what i'v come up: https://github.com/muxahuk/mongo-express/commit/9165273bf37edf8bc59d2a10127daca0353db653
it still requers some changes, maybe design improvments and missing `rename` for files renaming.
U could play around and say what do u think should be improved and how.

PS: Mark it as note, disscussion or something like these.

**Comment by wulfsolter** [comment]
Oh WOW!!!! That looks fantastic!!!!!!!

I've personally not needed/used GridFS as my production requirements are ~50kb documents x 1,000,000 but your implementation is very sound, and I know there are lots of people who will really like this.

I've no constructive suggestions to add regarding functionality, I know you'll get rename done, but would please ask that the code style matches the [JSCS](http://jscs.info/) preset for [AirBnB](https://github.com/airbnb/javascript) Not sure how your dev enviro is set up, but I have my Sublime Text configured to [lint as I write](https://github.com/SublimeLinter/SublimeLinter-jscs) and pre-commit hooks to ensure that it passes jscs. Feedback on why the [pre-commit hooks](https://github.com/andzdroid/mongo-express/blob/master/package.json#L56-L66) aren't working would be great?

**Comment by muxahuk** [comment]
about `pre-commit` - if your wondering why it doesn't works for me - problem must be that i use GitHub for windows, not command line..

I wanted to descuass/ask one question related to gridFS:
currently it creates `fs.files` and `fs,chunks` in each database, but there most likely will be usecases when your app will use more than 1 file storage brefix ( for ex. `fs.files`, `movie.files`, `user_uploaded.files` atc. ).
How should these be solved ? How we can provide user to list all files from different file storages ?

How i see it: we should create database ( and hide it from panel ) where we would store eny settings related to database ( like wich storage prefixes it has atc. ). These way we could be able to see all files in all storages.

Any suggestions ?

**Comment by wulfsolter** [comment]
Ah gotcha re pre-commit hooks :) I might look into making linting part of the Travis tests as I find linting helps prevent a lot of bugs from creeping in accidentally while JSCS style guides keep the source easier to read across multiple authors.

I'm all for creating a config DB, tools like PhpMyAdmin & pgAdmin do this, but that's a fair bit of work best saved for a later day once it gets necessary, which I don't believe it is yet...

The fallback behaviour should be that mongo-express doesn't need to look up any customised config in order to use GridFS, but sees in the list of databases pairs of with name endings of `.files` and `.chunks` and attempts to treat the pair as GridFS by providing an interface to add/remove files. As an admin interface, users should still be able to browse/update `.files` and `.chunks` databases, but without needing to add custom configuration settings treat them as GridFS.

We can get an array of GridFS buckets by analysing the list of databases, somewhere around
https://github.com/andzdroid/mongo-express/blob/53c446128cba9587fdc3e5c28b16f48fcb779941/db.js#L90 with a statement like

```
gridFSBuckets = _.map(_.filter(databases, function(el) { return el.substr(-6) === '.files' && _.intersection(databases, [el.slice(0, -6) + '.chunks']); }), function(el) { return el.slice(0, -6); });
```

which takes all databases, filters by having suffix of '.files' and also a corresponding '.chunks' in the DB list, then returns just the prefix name.

Once we have an array of GridFS buckets generated in db.updateDatabases, it should be pretty straight forward to list them in views/index.html, and create a view&route for upload/download/deleting inside a bucket similar to the "Collections" view.

**Comment by muxahuk** [comment]
That sound better than my solution. I'll stick to it.
